[project]
name = "rishi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.120.0",
    "google-genai>=1.46.0",
    "httpx>=0.28.1",
    "openai>=2.6.1",
    "python-dotenv>=1.1.1",
]
